# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcd0e97e28081554fe9a321ee339ce701ca8a0b5d7b59ed7c0b12d9428eb8c6e99f65b1c2634b81762852f6c8cd3ab07535347c5f2690f33a7ef0d980ddab793

test:
  secret_key_base: 9bd0f949cbbf696ee7781769bc72d630078d72dc1a7ed09475c979bd4d0d18ae3bc4c9e4dcc896b31505ba38f788e379428558d3fc99fe53fd00953c8eff520b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
